version: '3.1'

networks:
  backend:

services:
  postgres-db:
    image: postgres:14.3-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./dockerfiles/postgres:/var/lib/postgresql/data
    networks:
      backend:
    environment:
      POSTGRES_DB: rental-rooms
      POSTGRES_USER: rental-rooms
      POSTGRES_PASSWORD: rental-rooms

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      backend:
    depends_on:
      - postgres-db
      - mailhog
