version: '3.1'

networks:
  backend:

services:
  postgres-db:
    image: postgres:14.3-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./dockerfiles/postgres:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      POSTGRES_DB: rental-rooms
      POSTGRES_USER: rental-rooms
      POSTGRES_PASSWORD: rental-rooms

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - "1027:1025"
      - "8027:8025"

  app:
    build: .
    ports:
      - "8443:8443"
    networks:
      - backend
    depends_on:
      - postgres-db
      - mailhog
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/rental-rooms
      SPRING_DATASOURCE_USERNAME: rental-rooms
      SPRING_DATASOURCE_PASSWORD: rental-rooms
      SPRING_MAIL_HOST: host.docker.internal
      SPRING_MAIL_PORT: 1027
