CREATE TABLE CONFIRMATION_TOKEN(
   ID uuid,
   STATUS VARCHAR(255) NOT NULL,
   EXPIRATION_DATE date NOT NULL,
   USER_ID uuid UNIQUE NOT NULL,
   PRIMARY KEY (ID),
   CONSTRAINT CONFIRMATION_TOKEN_X_USER_ID
       FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
)